name: GhostyHome
version: '${project.version}'
main: de.ghosty.ghostyhome.GhostyHome
api-version: '1.21'
description: Home plugin with GUI, multi-language support and hex color codes.
authors: [Ghosty]

commands:
  home:
    description: Teleports you to your home or opens the home GUI.
    usage: /<command> [home-name]
    permission: ghostyhome.home
  sethome:
    description: Sets a home at your current position.
    usage: /<command> [home-name]
    permission: ghostyhome.sethome
  delhome:
    description: Deletes one of your homes.
    usage: /<command> <home-name>
    permission: ghostyhome.delhome
  adminhome:
    description: Admin command to view homes of other players.
    usage: /<command> [player]
    permission: ghostyhome.admin

permissions:
  ghostyhome.*:
    description: Full access to GhostyHome.
    default: op
    children:
      ghostyhome.home: true
      ghostyhome.sethome: true
      ghostyhome.delhome: true
      ghostyhome.admin: true

  ghostyhome.home:
    description: Allows using /home.
    default: true

  ghostyhome.sethome:
    description: Allows using /sethome.
    default: true

  ghostyhome.delhome:
    description: Allows using /delhome.
    default: true

  ghostyhome.admin:
    description: Allows using /adminhome to view homes of other players.
    default: op

  ghostyhome.homes.1:
    description: Allows up to 1 home.
    default: false
  ghostyhome.homes.2:
    description: Allows up to 2 homes.
    default: false
  ghostyhome.homes.3:
    description: Allows up to 3 homes.
    default: false
  ghostyhome.homes.5:
    description: Allows up to 5 homes.
    default: false
  ghostyhome.homes.10:
    description: Allows up to 10 homes.
    default: false
  ghostyhome.homes.25:
    description: Allows up to 25 homes.
    default: false
  ghostyhome.homes.50:
    description: Allows up to 50 homes.
    default: false
  ghostyhome.homes.100:
    description: Allows up to 100 homes.
    default: false
